version: "2"
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
linters:
  # We'll track the golangci-lint default linters manually
  # instead of letting them change without our control.
  default: none
  enable:
    # golangci-lint defaults:
    - errcheck
    - govet
    - ineffassign
    - staticcheck # gosimple has been merged inside the staticcheck.
    - unused

    # Our own extras:
    - nolintlint # lints nolint directives
    - revive
  settings:
    govet:
      # These govet checks are disabled by default, but they're useful.
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite

    errcheck:
      exclude-functions:
        # These methods can not fail.
        # They operate on an in-memory buffer.
        - (*go.uber.org/zap/buffer.Buffer).Write
        - (*go.uber.org/zap/buffer.Buffer).WriteByte
        - (*go.uber.org/zap/buffer.Buffer).WriteString

        - (*go.uber.org/zap/zapio.Writer).Close
        - (*go.uber.org/zap/zapio.Writer).Sync
        - (*go.uber.org/zap/zapio.Writer).Write
        # Write to zapio.Writer cannot fail,
        # so io.WriteString on it cannot fail.
        - io.WriteString(*go.uber.org/zap/zapio.Writer)

        # Writing a plain string to a fmt.State cannot fail.
        - io.WriteString(fmt.State)
  exclusions:
    generated: lax
    # Don't ignore some of the issues that golangci-lint considers okay.
    # This includes documenting all exported entities.
    # exclude-use-default: false

    rules:
      # Don't warn on unused parameters.
      # Parameter names are useful; replacing them with '_' is undesirable.
      - linters: [revive]
        text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'

      # staticcheck already has smarter checks for empty blocks.
      # revive's empty-block linter has false positives.
      # For example, a riting this, the following is not allowed.
      #   for foo() { }
      - linters: [revive]
        text: 'empty-block: this block is empty, you can remove it'

      # Ignore logger.Sync() errcheck failures in example_test.go
      # since those are intended to be uncomplicated examples.
      - linters: [errcheck]
        path: example_test.go
        text: 'Error return value of `logger.Sync` is not checked'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # Print all issues reported by all linters.
  max-issues-per-linter: 0
  max-same-issues: 0
