version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - nolintlint
    - revive
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (*go.uber.org/zap/buffer.Buffer).Write
        - (*go.uber.org/zap/buffer.Buffer).WriteByte
        - (*go.uber.org/zap/buffer.Buffer).WriteString
        - (*go.uber.org/zap/zapio.Writer).Close
        - (*go.uber.org/zap/zapio.Writer).Sync
        - (*go.uber.org/zap/zapio.Writer).Write
        - io.WriteString(*go.uber.org/zap/zapio.Writer)
        - io.WriteString(fmt.State)
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'
      - linters:
          - revive
        text: 'empty-block: this block is empty, you can remove it'
      - linters:
          - errcheck
        path: example_test.go
        text: Error return value of `logger.Sync` is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
